projet_m2_bi:
  target: exploration-dev
  outputs:
    exploration-dev:
      type: bigquery
      method: oauth
      project: "decisive-plasma-473714-i8"
      dataset: dev_projet_m2_mi_warehouse
      threads: 1
      location: EU

    prod:
      type: bigquery
      method: oauth
      project: "decisive-plasma-473714-i8"
      dataset: prod_projet_m2_mi_warehouse
      threads: 4
      location: EU

